name: cangyan
description: "A new Flutter project."
publish_to: "none"
version: 0.2.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core:
    path: builder
  flutter_rust_bridge: 2.5.0
  path_provider: ^2.1.4
  share_plus: ^10.1.2
  file_picker: ^8.1.4
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.4.3
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
