name: cangyan

version: 0.4.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rinf: ^8.8.0
  meta: ^1.17.0
  tuple: ^2.0.2
  window_manager: ^0.5.1
  desktop_drop: ^0.7.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
