name: cangyan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core:
    path: builder
  flutter_rust_bridge: 2.5.0
  path_provider: ^2.1.4
  marquee: ^2.3.0
  file_picker: ^8.1.3

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
