name: cangyan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core:
    path: builder
  flutter_rust_bridge: 2.5.0
  path_provider: ^2.1.4
  share_plus: ^10.1.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
