[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.5.0"
cyfile = { git = "https://github.com/Goolnn/cyfile", tag = "v0.2.1" }
