// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../cyfile/summary.dart';
import 'create.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HomeState>>
abstract class HomeState implements RustOpaqueInterface {
  CreateState create();

  Future<List<Summary>> load();

  factory HomeState({required String workspace}) =>
      RustLib.instance.api.crateApiStatesHomeHomeStateNew(workspace: workspace);
}
