// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../cyfile/summary.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < File > >>>
abstract class ArcMutexFile implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InfoState>>
abstract class InfoState implements RustOpaqueInterface {
  static InfoState from({required Summary summary}) =>
      RustLib.instance.api.crateApiStatesInfoInfoStateFrom(summary: summary);

  factory InfoState({required ArcMutexFile file}) =>
      RustLib.instance.api.crateApiStatesInfoInfoStateNew(file: file);

  Summary summary();
}
