[package]
name = "hub"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
wildcard_imports = "deny"

[dependencies]
rinf = "8.8.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.0", features = ["rt", "macros", "time"] }
async-trait = "0.1.87"
messages = "0.3.1"

[target.'cfg(target_os = "windows")'.dependencies]
directories = "6.0.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
