// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'editor.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Pages>>
abstract class Pages implements RustOpaqueInterface {
  Editor edit({required BigInt index});

  List<Uint8List> images();

  void insertPageAfter({required BigInt index, required List<int> image});

  void insertPageBefore({required BigInt index, required List<int> image});

  void movePageTo({required BigInt from, required BigInt to});

  factory Pages({required ArcMutexFile file}) =>
      RustLib.instance.api.crateApiToolsPagesPagesNew(file: file);

  void removePage({required BigInt index});
}
