// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'editor.dart';
import 'file.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'summary.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Workspace>>
abstract class Workspace implements RustOpaqueInterface {
  bool check({required String title});

  Future<File> create({required String title, required List<Uint8List> images});

  Future<ArcMutexFile> import_(
      {required String title, required List<int> data});

  Future<List<Summary>> load();

  factory Workspace({required String path}) =>
      RustLib.instance.api.crateApiToolsWorkspaceWorkspaceNew(path: path);
}
