// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'credit.dart';
import 'date.dart';
import 'note.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'page.dart';
import 'text.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Project>>
abstract class Project implements RustOpaqueInterface {
  String category();

  Uint8List? cover();

  Date createdDate();

  Map<Credit, Set<String>> credits();

  void delete();

  (int, int) number();

  int pageCount();

  List<Page> pages();

  double progress();

  Date savedDate();

  void setCategory({required String category});

  void setCover({required List<int> cover});

  void setCredits({required Map<Credit, Set<String>> credits});

  void setNumber({required (int, int) number});

  void setPages({required List<Page> pages});

  void setTitle({required String title});

  String title();
}
