// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'credit.dart';
import 'date.dart';
import 'note.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'page.dart';
import 'text.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

class Project {
  Uint8List cover;
  String category;
  String title;
  (int, int) number;
  String comment;
  Date createdDate;
  Date updatedDate;
  Map<Credit, Set<String>> credits;
  List<Page> pages;

  Project({
    required this.cover,
    required this.category,
    required this.title,
    required this.number,
    required this.comment,
    required this.createdDate,
    required this.updatedDate,
    required this.credits,
    required this.pages,
  });

  @override
  int get hashCode =>
      cover.hashCode ^
      category.hashCode ^
      title.hashCode ^
      number.hashCode ^
      comment.hashCode ^
      createdDate.hashCode ^
      updatedDate.hashCode ^
      credits.hashCode ^
      pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Project &&
          runtimeType == other.runtimeType &&
          cover == other.cover &&
          category == other.category &&
          title == other.title &&
          number == other.number &&
          comment == other.comment &&
          createdDate == other.createdDate &&
          updatedDate == other.updatedDate &&
          credits == other.credits &&
          pages == other.pages;
}
