// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'credit.dart';
import 'date.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Summary>>
abstract class Summary implements RustOpaqueInterface {
  String category();

  String comment();

  Uint8List cover();

  Date createdDate();

  Map<Credit, Set<String>> credits();

  (int, int) number();

  BigInt pageCount();

  List<Uint8List> pages();

  String title();

  Date updatedDate();
}
