// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class Config {
  String? workspace;
  bool checkUpdate;
  bool previewFeatures;

  Config.raw({
    this.workspace,
    required this.checkUpdate,
    required this.previewFeatures,
  });

  static Config empty() => RustLib.instance.api.crateApiConfigConfigEmpty();

  factory Config({required String value}) =>
      RustLib.instance.api.crateApiConfigConfigNew(value: value);

  @override
  String toString() => RustLib.instance.api.crateApiConfigConfigToString(
        that: this,
      );

  @override
  int get hashCode =>
      workspace.hashCode ^ checkUpdate.hashCode ^ previewFeatures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          workspace == other.workspace &&
          checkUpdate == other.checkUpdate &&
          previewFeatures == other.previewFeatures;
}
